theme = "catppuccin_mocha"
[editor]
gutters = ["diagnostics", "spacer", "diff"]

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[keys.normal]
f = "goto_word"
C-q = [":pipe gpt -"]
